source 'http://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'

# MongoDB Adapter
gem 'mongoid', '~> 4.0.2'
# gem 'mongoid', git: 'git://github.com/mongoid/mongoid.git'

# JSON parsing and conversion
gem 'multi_json'

# GeoJSON Mapping
gem 'leaflet-rails'

# HTTP requests testing
gem 'rest-client'

# user auth, roles, & permissions
gem 'devise'
gem 'cancancan', '~> 1.9'
gem 'role_model'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'bootstrap_form'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

# Document API
gem 'apipie-rails'

# Time Zone Information
gem 'tzinfo'
gem 'tzinfo-data', platforms: [:x64_mingw, :mingw, :mswin]

#group :development, :test do
#  gem 'capistrano'
#end


