source 'http://rubygems.org'

# there is an issue with higher versions of nokogiri
gem 'nokogiri', '1.6.8.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'

# MongoDB Adapter
gem 'mongoid', '~> 4.0.2'
# gem 'mongoid', git: 'git://github.com/mongoid/mongoid.git'

# JSON parsing and conversion
gem 'multi_json'

# GeoJSON Mapping
gem 'leaflet-rails'

# HTTP requests testing
gem 'rest-client'

# pagination
gem 'kaminari'

# user auth, roles, & permissions
gem 'devise', '~> 3.5'
gem 'cancancan', '~> 1.9'
gem 'role_model'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'bootstrap_form'

# Use Uglifier as compressor for JavaScript assets
gem 'libv8', :platforms => :ruby
gem 'execjs'
gem 'therubyracer', :platforms => :ruby

gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# there is an issue with 'coffee-script source' >= 1.9.0 on windows.
gem 'coffee-script-source', '1.8.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

# Document API
gem 'apipie-rails'

# Time Zone Information
gem 'tzinfo'
gem 'tzinfo-data', platforms: [:x64_mingw, :mingw, :mswin]

# group :development, :test do
#  gem 'capistrano'
# end

group :development do
  #gem "rails-erd"
  gem "railroady" # railroady -o models.dot -M && dot -Tpng models.dot > models.png
end

